"""auth — the template's one table

Revision ID: 5ca7ea527fc1
Revises:
Create Date: 2026-08-30 01:06:36.832031

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5ca7ea527fc1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), server_default="USER", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auth", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_code"), ["code"], unique=True)
        batch_op.create_index(batch_op.f("ix_auth_email"), ["email"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auth", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_email"))
        batch_op.drop_index(batch_op.f("ix_auth_code"))

    op.drop_table("auth")
    # ### end Alembic commands ###
